dist: xenial

os:
- linux

language: go

go:
- "1.13.x"
- tip

matrix:
  allow_failures:
  - go: tip

env:
- GOLANGCI_RELEASE="v1.23.1"

before_install:
- GO111MODULE=off go get github.com/mattn/goveralls
- GO111MODULE=off go get github.com/lawrencewoodman/roveralls
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}

script:
- make test
- make lint
- travis_wait 20 roveralls
- goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
