dist: trusty

os:
- linux

language: go

go:
- 1.9
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure -vendor-only
- go get github.com/mattn/goveralls
- go get github.com/alecthomas/gometalinter

install:
- gometalinter --install

script:
- vendor/github.com/kubernetes/repo-infra/verify/verify-boilerplate.sh --rootdir=$(pwd)
- vendor/github.com/kubernetes/repo-infra/verify/verify-go-src.sh -v --rootdir $(pwd)
- travis_wait 20 goveralls -service=travis-ci
