apiVersion: v2
name: external-dns
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
type: application
version: 1.18.0
appVersion: 0.18.0
keywords:
  - kubernetes
  - k8s
  - externaldns
  - external-dns
  - dns
  - service
  - ingress
  - gateway
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
sources:
  - https://github.com/kubernetes-sigs/external-dns/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations: {}
