name: update-versions-with-renovate

on:
  push:
    branches: [main, master]
  schedule:
    # https://crontab.guru/
    # once a day
    - cron: '0 0 * * *'

jobs:
  update-versions-with-renovate:
    runs-on: ubuntu-latest
    if: github.repository == 'kubernetes-sigs/external-dns'
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      # https://github.com/renovatebot/github-action
      - name: self-hosted renovate
        uses: renovatebot/github-action@v43.0.1
        with:
          # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate-config.js
        env:
          LOG_LEVEL: info
