name: Lint

on:
  push:
    branches: [ master, rc ]
  pull_request:
    branches: [ master, rc ]

jobs:
  lint:
    name: Markdown, Go and OAS
    runs-on: ubuntu-latest
    permissions:
      contents: read  #  to fetch code (actions/checkout)
      checks: write
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Lint markdown
      uses: nosborn/github-action-markdown-cli@v3.4.0
      with:
        files: '.'
        config_file: ".markdownlint.json"

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Lint go code
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=30m
        version: v1.63

      # Run Spectral
    - name: Lint OpenAPI spec
      uses: stoplightio/spectral-action@2ad0b9302e32a77c1caccf474a9b2191a8060d83 # v0.8.11
      with:
        file_glob: 'api/*.yaml'
